### ISSUE TITLE
help-files in shared/doc

### ISSUE THREAD

**Issue by oberon2007** [manjaro/desktop-settings#17]
No package installs the i3-help files now since they have been moved from **/etc/skel** and **live/etc/skel** to **shared/doc**. How can I use them again?

**Comment by philmmanjaro** [comment]
Why got they moved to **shared/doc** the first place?

**Comment by oberon2007** [comment]
They got "cleaned up" ;)
https://github.com/manjaro/manjaro-tools-iso-profiles/commit/b1013a0539cee5bfd6d8e5030fc84353d9b9edfe

**Comment by philmmanjaro** [comment]
Well, we have to find a solution for overlays in live-session also for skel folders. Since it is just needed in live-session it is fine for me to have them in iso-profiles in the given live-overlay. 

@artoo, seems you're on a cleaning spree. Please include the rest of the team a little more and don't make decisions alone on this. Soon or later some maintainer might get pissed when this goes on like this soon or later ...

**Comment by udeved** [comment]
I moved them to shared, because there is no point to have them in several profiles.
They should be packaged I think, just to prevent we get again redundant stuff.
