### ISSUE TITLE
desktop-settings should depend on the theme packages

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/desktop-settings#35]
For now we set our themes in our desktop-settings packages. However we don't yet add the used themes as dependencies. This should we think again thru. Otherwise somebody installs the setting and it won't work as the matching theme was not installed.

**Comment by philmmanjaro** [comment]
https://github.com/manjaro/desktop-settings/commit/a4bfb61777463db62c03c6d66e5670acdd14dfe2

**Comment by philmmanjaro** [comment]
Added dependencies to **xfce-settings** https://github.com/manjaro/packages-extra/commit/cc07d00e6864384acedf12557071ddcdd827a669

**Comment by germanfr** [comment]
Hi, I have a little issue here. 

There's a new dependency for `manjaro-cinnamon-settings` which is a pack of thousands of icon themes called `vibrancy-colors`. It's very annoying because they are a lot and I can't uninstall them without removing `manjaro-cinnamon-settings` package. Well... I actually can but I have to reinstall it on every update. If it was one or two I wouldn't obviously care, but there's a crazy ammount of them. I don't understand why is it required if it's just a theme. Could you please remove it from the dependencies or at least add it as optional?

Regards, Germán.

**Comment by oberon2007** [comment]
Yeah, I know... Was also unsure in the first place and then decided since the different color versions are actually only symlinks with just one different folder icon for each color. But I understand that it's probably annoying to have your theme settings spammed like that...
Problem is just that when someone just installed the settings package, config will be broken without the dependency...

**Comment by germanfr** [comment]
I don't understand of these things very much but can't you install it separately without it being a dependency? Like for example if you decide to install a text editor by default.

**Comment by Ste74** [comment]
I think now all edition install theming with desktop-settings as depend a part bspwm and our jwm . Seem also xfce and kde profile install it .. can be closed this ?

**Comment by oberon2007** [comment]
I think you're right :)
